language: python
python:
  - "pypy3"
  - "3.4"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script: make test

services:
  - mongodb